worker_processes auto;
events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;
        root  /usr/share/nginx/html;
        index index.csr.html index.html;

        location / {
            try_files $uri $uri/ /index.csr.html;
        }

        # Cache de longa duração para arquivos com hash no nome
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
